name: sample

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"

      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: List files in this repository
        run: |
          echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7::Error in app.js"
          echo "The repository ${{ github.repository }} contains the following
          files:"
          tree
      - name: Set color
        id: color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "${{ steps.color-generator.outputs.SELECTED_COLOR }}"
      - name: Set the value
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
          echo "${{ env.action_state }}" # This will output 'yellow'
