name: sample

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"

      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: List files in this repository
        run: |
          echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7::Error in app.js"
          echo "The repository ${{ github.repository }} contains the following
          files:"
          tree
      - name: Set color
        id: color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "${{ steps.color-generator.outputs.SELECTED_COLOR }}"
      - name: Set the value
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
      - run: echo "${{ env.action_state }}" # This will output 'yellow'
      - run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
      - run: echo '### Love this feature! :medal_sports:' >> $GITHUB_STEP_SUMMARY
      - run: echo '<h1>Great feature!</h1>' >> $GITHUB_STEP_SUMMARY
      - run: |
          echo "## Test results" >> "$GITHUB_STEP_SUMMARY"
          echo "| **Test Name** | **Result**|" >> "$GITHUB_STEP_SUMMARY"
          echo "|--|--|" >> "$GITHUB_STEP_SUMMARY"
          echo "| validate numbers are > 0 |:white_check_mark: |" >> "$GITHUB_STEP_SUMMARY"
          echo "| validate numbers are < 10 |:white_check_mark: |" >> "$GITHUB_STEP_SUMMARY"
          echo "| validate numbers are odd |:x: |" >> "$GITHUB_STEP_SUMMARY"
          echo "| validate numbers are even|:white_check_mark: |" >> "$GITHUB_STEP_SUMMARY"
      - name: composite
        id: composite-step
        uses: ./
        with:
          var1: 'bbb'
      - name: output-composite
        run: echo ${{ steps.composite-step.outputs.out1 }}
